### ISSUE TITLE
[regression in 2.0.8] Error: Version 3.11 of the dune language is not supported.

### ISSUE THREAD

**Issue by yurivict** [abella-prover/abella#148] opened 2023-11-14 00:41 UTC
The build of the 2.0.8 version fails:
```
dune build src/abella.exe src/abella_doc.exe src/abella_dep.exe
File "dune-project", line 1, characters 11-15:
1 | (lang dune 3.11)
               ^^^^
Error: Version 3.11 of the dune language is not supported.
Supported versions of this extension in version 3.11 of the dune language:
- 1.0 to 1.12
- 2.0 to 2.9
- 3.0 to 3.7
```

ocaml-dune-3.7.1
ocaml-ocamlbuild-0.14.2_2
FreeBSD 13.2

**Comment by chaudhuri** [comment] 2023-11-14 00:51
Abella has only been tested to build with Dune 3.11+. If you use opam it should automatically upgrade Dune if needed. I'll check in the morning if earlier Dune releases work as well.

**Comment by yurivict** [comment] 2023-11-14 00:55
I am trying to upgrade the FreeBSD port, and it has to use packages for ocaml* dependencies.

**Comment by chaudhuri** [comment] 2023-11-15 16:05
Lowered the Dune lang to 3.7 in 0c5a1faf45bb627a1a5a86ae588a13ec2791ed4e. Please see if it compiles for you.

Unfortunately it's too late for 2.0.8, but we can release a 2.0.8.1 with this change if you want.

**Comment by chaudhuri** [comment] 2023-11-16 18:05
Closing this because this is not a regression. Please fix the dependencies you've listed in your `Makefile`. Abella's dependencies can be found in the `abella.opam` file.

**Closed by chaudhuri** 2023-11-16 18:05 UTC

**Comment by chaudhuri** [comment] 2024-04-05 11:35
Continued in #154
