### ISSUE TITLE
Regression: Ensure should error on implicit subordination

### ISSUE THREAD

**Issue by robblanco** [abella-prover/abella#60] opened 2016-04-26 17:57 UTC
From `test/test_subordination.ml`:

    Failure: Abella:3:Subordination:7:Ensure should error on implicit subordination
    
    OUnit: expected exception Failure("Type tm cannot be made subordinate to tp without explicit declaration"), but no exception was not raised.

**Comment by chaudhuri** [comment] 2016-04-26 22:10
This is not a bug. We no longer do "implicit subordination" (since a7df40b7e45b8).

**Comment by chaudhuri** [comment] 2016-04-26 22:11
Err, maybe we close this after we update the test.

**Comment by robblanco** [comment] 2016-04-26 22:22
So the solution is simply to remove that test?

**Comment by chaudhuri** [comment] 2016-04-26 22:27
Yeah, perhaps this particular issue is solved by removing the test. However, we need to think up some new tests to cover the new subordination mechanisms. I'll think about it when I have a bit less blood in my caffeine stream.

**Comment by chaudhuri** [comment] 2016-04-26 22:28
Ping @yvting in case he is interested.

**Closed** 2016-04-28 13:09 UTC
