### ISSUE TITLE
Hypothesis disappears on case error

### ISSUE THREAD

**Issue by lambdacalculator** [abella-prover/abella#41] opened 2015-08-17 20:04 UTC
When mistakenly performing, say, `case H5` on a backchaining hypothesis where the bracketed formula is a variable, I get the usual error message ("Error: Failure("Head of backchained clause unknown...")"), but then the proof state I'm returned to is missing hypothesis `H5`.

**Comment by chaudhuri** [comment] 2015-08-17 20:09
I cannot reproduce this on `master`. Can you provide a small example where you see this behavior?

**Comment by chaudhuri** [comment] 2015-10-20 22:11
I'm closing this as irreproducible on my end. Feel free to reopen if you submit an example that shows the issue.

**Comment by lambdacalculator** [comment] 2015-10-31 21:06
This happened to me again today, but when I tried to isolate the problem with a simple example, I wasn't able to reproduce it. Here, at least, is the original snippet showing the issue:

    Subgoal 2.1:

    Variables: Psi N
    H1 : dimctx (dblck n1 N :: Psi n1)
    H3 : dblck n1 N = dblck n1 N -> false
    ============================
     {Psi n1 |- dblck n1 N}

    Subgoal 2.2 is:
     {Psi n1 |- dblck n1 N}

    dblck_str < case H3.
    Error: Invalid_argument("dblck n1 N = dblck n1 N -> false")
    Subgoal 2.1:

    Variables: Psi N
    H1 : dimctx (dblck n1 N :: Psi n1)
    ============================
     {Psi n1 |- dblck n1 N}

    Subgoal 2.2 is:
     {Psi n1 |- dblck n1 N}

You can see that, after the error-producing `case H3`, the hypothesis `H3` disappears from the proof state. Also, this has nothing to do with `undo`, since I reproducibly get the error on a fresh run of Abella (2.0.4-dev). I saved a copy of the .sig, .mod, and .thm files that reproduce the problem, but I really don't want to share those (publicly or privately) unless absolutely necessary.

**Comment by chaudhuri** [comment] 2015-10-31 21:38
Thanks. Looking into it now.

**Comment by chaudhuri** [comment] 2015-10-31 22:12
There are a number of things that may be going wrong, but looking at it manually I couldn't spot anything in the code path from the parser to the error on this invocation of `case` that would cause a change to the goal that is not automatically undone on an exception.

Here's my attempt to recreate your exact proof state, which doesn't show the bug.

    Kind i type.
    
    Type dimctx olist -> prop.
    Type dblck i -> i -> o.
    
    Theorem dblck_str : forall Psi N, nabla u,
      dimctx (dblck u N :: Psi u) ->
      ((dblck u N = dblck u N -> false) \/ (dblck u N = dblck u N)) ->
      {Psi u |- dblck u N}.
    intros.
    fake : assert true \/ true. case fake. skip.
    case H2.
    %% Should now look like this from #41:
    %%
    %% Subgoal 2.1:
    %%
    %% Variables: Psi N
    %% H1 : dimctx (dblck n1 N :: Psi n1)
    %% H3 : dblck n1 N = dblck n1 N -> false
    %% ============================
    %%  {Psi n1 |- dblck n1 N}
    %%
    %% Subgoal 2.2 is:
    %%  {Psi n1 |- dblck n1 N}
    case H3.

Can you modify it a bit so that it does show the bug?

If that's not easy to do (as I suspect), I will need to see your development source, unfortunately. I need to see the failure on my end to even begin the debugging process. E-mail it to me and I promise to use it only for debugging purposes on this issue and delete it afterwards.

**Comment by chaudhuri** [comment] 2015-11-02 13:29
(Summary of private correspondence with @lambdacalculator)

The issue only shows up with the `-i` flag. The dummy example in my previous comment already shows the problem -- the actual original development files are not needed.

**Closed** 2015-11-02 13:43 UTC
Labels: bug
